### PR TITLE
Add Presto web connector for Tableau

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
This PR adds support for a web connector for Tableau that enables running SQL queries from Tableau against Presto.

### CODE REVIEW

**Comment by KBP-TDC** [comment]
Hi Nezih!
This seems very cool! Is there any word on the web connectors supporting live mode in the future?

**Comment by nezihyigitbasi** [comment]
Kamil, unfortunately I don't have any info about it.

**Comment by nezihyigitbasi** [comment]
@cawallin What do you mean by "streaming Tableau access"? If you mean live mode then Tableau needs to make changes to their product as their web connector API only supports the extract mode right now.

**Comment by cawallin** [comment]
@nezihyigitbasi My apologies for the post that nearly duplicated Kamil's, I didn't see it. My question was more about what was blocking connecting directly to Tableau, which would also allow live mode. This itself is great though!

**Comment by nezihyigitbasi** [comment]
@haozhun Any plans to get this merged? I have just updated this PR for the latest Tableau release (9.1).

**Comment by haozhun** [comment]
Thank you for keeping this up to date. And sorry about the delay. There was some discussion about the URL this needs to be in, the documentation location this needs to be in, etc. But in any case, we definitely should get this merged sooner than later.

**Comment by nezihyigitbasi** [comment]
fixed another bug + cleaned up a bit.

**Comment by haozhun** [comment]
Hi @nezihyigitbasi. I discussed about this pull request with @martint. The major concern here is about security.

1. Right now, Presto server is susceptible to cross-origin writes and potentially cross-origin reads. This web connector adds another endpoint where such attack can target. Have you considered putting this in a separate service? Is there any particular reason this need to be inside Presto?
2. If we add additional security to the presto server, will that break web connector?

Additionally, we have 1 questions:

1. The script currently references two external scripts. We'd like to put these scripts in Presto. For jQuery, it's simple and straightforward. For tableauwdc, is that possible and legal?

I apologize for my ignorance of tableau. Please excuse me if any of my comments don't make sense.

**Comment by nezihyigitbasi** [comment]
@haozhun @martint thanks for looking at this.

1. The reason I put the web connector inside Presto is two fold. One is to get rid of cross domain requests so that the web connector and Presto's REST services are in the same domain. Second, I wanted to make it available to the Presto community. What do you mean by "putting this in a separate service"? Do you mean like deploying it on a separate machine (in which case we will make cross domain requests)? We can for sure deploy the web connector somewhere else and then configure a proxy to get rid of the cors restrictions. 
2. What kind of security are we talking about here? It may or may not depending on the answer.
3. Unfortunately I don't know this one. But I will check it with Tableau and update this thread.

**Comment by nezihyigitbasi** [comment]
Tableau team told me that the web connector javascript file is MIT licensed and already open source [here](https://github.com/tableau/webdataconnector/tree/gh-pages/js). So I think we can include it as long as we mention that this file is MIT licensed, see the [MIT license](http://opensource.org/licenses/mit-license.php) description.

**Comment by nezihyigitbasi** [comment]
@haozhun @martint Updated the PR to include the vendor files.

**Comment by nezihyigitbasi** [comment]
@haozhun Updated the PR with the following:

- Added support for setting session parameters
- The connector now handles failures more gracefully. Previously it was causing Tableau client to hang on exceptions. Now it fails with a descriptive error message.

**Comment by haozhun** [comment]
I have merged this pull request.

I fixed some formatting, moved the file into a subdirectory, added copyright notes, modified document slightly, removed meta flag that would be ignored by browser anyways, and added character-encoding meta flag.

I do want to point out that using `async:false` is really bad. See http://stackoverflow.com/questions/1457690/jquery-ajax-success-anonymous-function-scope for how to fix it.

**Pull request closed without merging**
