### PR TITLE
Initial decimal support

### PR DESCRIPTION
**Pull request by losipiuk**
Series of patches for partial implementation of `DECIMAL(x,y)` support (#2797).
Patches base on @dain's PR #2478 which adds support for parametrising data types with long literal arguments.

This PR introduces `DECIMAL(x,y)` data type. Precision up to 38 is supported.

Two implementations are provided. For decimals up to precision 17 `long` based implementation is 
used. For larger precision `Slice` based implementation.

There is support for defining `DECIMAL` literals. For now with `DECIMAL 2323.3434` syntax.
Later semantics should be changed so standard `34343.4343` defines DECIMAL instead of `DOUBLE PRECISION`.

As for functions only `+` operator is defined for now. We wanted to validated overall approach before moving too much forward. @sopel39 proposed more concise syntax for defining subsequent operators/functions in https://github.com/facebook/presto/issues/2797#issuecomment-123297916.

cc: @ilfrin

### CODE REVIEW

**Comment by cberner** [comment]
This PR is much too big to review in one piece. Can you break it up into a series of smaller PRs (ideally not more than ~1k lines each) at its logical boundaries? If we still have one that's a bit bigger that's fine, but 6k+ lines is just too big to review

**Comment by sopel39** [comment]
@cberner I have cleaned commits so that no commit is greater than 1K. However, commits depend on previous commits incrementally so it would be hard to make each commit a separate pull request. Do you think this form is OK for you to review? In total there is about 6K-7K additions and few hundreds deletions.

**Comment by cberner** [comment]
@sopel39 the difficulty isn't in the commits being large. It's that the whole PR is large, which makes it hard to merge and review. I find that I can review 1-2k lines of code in a day (although this very much depends on the complexity), so reviewing this would take a full week; it's very difficult to find an entire week that I can dedicate to one PR.

For an example of a feature we merged in smaller pieces, see all the PRs that added structural types to Presto (it was a long series of PRs from me, @miniway and @haozhun). Skimming through the list of files that were changed it looks like we should be able to break this up into a series of PRs that incrementally add this functionality:
1. Change parser and type system to support dependent type computation (maybe even break this into one that adds the type support and another that adds the function support)
2.a Add `varchar(x)`
2.b Add `varchar(x)` functions (this could be combined with 2.a if they're not a lot of code)
3. Add `decimal` type
4. Add functions for `decimal` type
5. Add support for `decimal` type to ORC reader
6. Add support for `decimal` type to Hive

Splitting this into ~7 PRs like that would make it much easier to review, and there seem to be a number of logical milestones like I laid out above.

**Comment by sopel39** [comment]
@cberner Actually `varchar(x)` is not our patch, but @dain. Would be great if you review it first: https://github.com/facebook/presto/pull/2478. We only based DECIMAL on it. After `varchar(x)` is pushed, we could make separated pull requests from our branch (if that is preferable).

**Comment by cberner** [comment]
Ah yes, I see now. It looks like @martint is reviewing that PR. I'll take a look at this one after it has been merged.

**Comment by losipiuk** [comment]
Closing for now as we are working on discussed changes to this patch

**Comment by linqer** [comment]
How about bigdecimal now, we are waiting for this feature release.

**Pull request closed without merging**
