### PR TITLE
Array type support negative subscript

### PR DESCRIPTION
**Pull request by yaoxin226**
Make Array support negative subscript.

Array[ -k ] returns the kth element to the last.

### CODE REVIEW

**Comment by electrum** [comment]
Thanks for sending this, but I don't think we can add this as it violates the required ANSI SQL behavior for the *array element reference* operator. See section 6.23 of SQL:2011:

> General Rules
> 2) Let *i* be the value of &lt;numeric value expression&gt;.
> Case:
> a) If *i* is greater than zero and less than or equal to the cardinality of &lt;array value expression&gt;, then the result of &lt;array element reference&gt; is the value of the *i*-th element of the value of &lt;array value expression&gt;.
> b) Otherwise, an exception condition is raised: *data exception — array element error*.

I agree this is useful functionality, so we could add this as a custom function.

**Comment by yaoxin226** [comment]
Thanks @electrum for your reply.
I understand we should follow the ANSI SQL.

So do you think we can add a function like this:
array_get(array, index) -> V
   if index in [1, array_length] same as subscript
   else if index in [-array_length, -1], then return the abs(index) th element to the last 
   else throw exception

**Comment by yaoxin226** [comment]
The SQL:2011 is you referenced, do we have a free community version or something? Seems like this iso version is not free to look up.
http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=53681

**Comment by yaoxin226** [comment]
I have created a new PR #2793  to add this functionality as a array function.  Could you take a look when you have time @electrum ? Thanks.

**Comment by electrum** [comment]
Unfortunately, the standard is rather expensive, and you have to purchase each part separately, but the draft versions are available if you search for them: http://jtc1sc32.org/doc/N2301-2350/32N2311T-text_for_ballot-CD_9075-2.pdf

**Pull request closed without merging**
