### PR TITLE
Minor Parquet reader cleanup

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
This PR removes some unused fields, and removes a redundant null check (fileReader is guaranteed to be non-null as it is initialized in the constructor)

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
@zhenxiao can you please review?

**Comment by zhenxiao** [comment]
looks good to me. I did some refactoring and bug fixing at:
https://github.com/facebook/presto/pull/4000
some of them are resolved at that PR. Could u please rebase on that, or make it a dependency?

**Comment by nezihyigitbasi** [comment]
@zhenxiao why don't you cherry pick this one, it would be easier. Then I can close this.

**Comment by zhenxiao** [comment]
good idea. get it merged:
https://github.com/facebook/presto/pull/4000

**Comment by nezihyigitbasi** [comment]
OK closing this one then.

**Pull request closed without merging**
