### PR TITLE
Append nulls for missing values in Parquet.

### LINKED ISSUE #3699: Fix error when reading a nested struct with missing optional fields in Parquet
To reproduce, have the schema like this, with the "firstOptionalInt" missing, and "secondString" as some string bigger than 8 characters. and run a select * query on it.

    (justFirstNonImportantThing BIGINT,
     aNestedStruct STRUCT(
            firstOptionalInt BIGINT,
            secondString STRING))

The relevant part of stacktrace looks something like this:

    Caused by: java.lang.IllegalStateException: Expected entry size to be exactly 8 but was 12

        at com.facebook.presto.spi.block.FixedWidthBlockBuilder.closeEntry(FixedWidthBlockBuilder.java:175)

        at com.facebook.presto.spi.block.InterleavedBlockBuilder.closeEntry(InterleavedBlockBuilder.java:210)

        at com.facebook.presto.spi.block.ArrayElementBlockWriter.closeEntry(ArrayElementBlockWriter.java:118)

        at com.facebook.presto.spi.type.VarbinaryType.writeSlice(VarbinaryType.java:109)

        ...

The problem is that the BlockBuilder's entryAdded() function is called only for the values that are present. So the "secondString" is being written into the FixedWidthBlockBuilder that was meant for the BIGINT before this. In this particular case, string size was 12.

### PR DESCRIPTION
**Pull request by saileshmittal**
Parquet only calls converts for which it found the values. The missing
values are not reported. The BlockBuilder must be appended with
nulls for the missing values based on fieldIndex of the currently
read value by Parquet. Fixes #3699

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
@saileshmittal can you please add some unit tests for your changes? @dain what's the best place to add such tests?

**Comment by saileshmittal** [comment]
@dain, @nezihyigitbasi, Could you tell where I can add these unit tests?

**Comment by nezihyigitbasi** [comment]
@saileshmittal I guess #3716 looks like a good place to add such tests once it's merged.

**Comment by dain** [comment]
This should be covered by `TestHiveFileFormats`

**Comment by saileshmittal** [comment]
@nezihyigitbasi , @dain, Thanks for pointing out the tests. I have added a couple that cover this patch.

**Comment by saileshmittal** [comment]
@dain @nezihyigitbasi Do you have any comments?

**Comment by saileshmittal** [comment]
Hi @dain , saw some changes in parquet reader. Does that solve this issue as well?

**Comment by dain** [comment]
@saileshmittal I don't know.  I have been very busy lately and haven't had time to track this.

**Comment by jwills** [comment]
FWIW, we're using this patch at Slack for our parquet/presto data, and would love to have it merged upstream.

**Comment by dain** [comment]
Merged, thanks!

**Pull request closed without merging**
