### PR TITLE
show partitions fails

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
The ``defaultValue`` is set to ``null`` instead of ``Optional.empty()`` when constructing the ``SearchedCaseExpression``, causing a NPE later on. This PR fixes that.

```
presto:default> show partitions from my_table;
Query 20150108_223912_00053_nig3u failed: null
java.lang.NullPointerException
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.getCaseResultExpressions(ExpressionAnalyzer.java:424)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitSearchedCaseExpression(ExpressionAnalyzer.java:385)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitSearchedCaseExpression(ExpressionAnalyzer.java:180)
        at com.facebook.presto.sql.tree.SearchedCaseExpression.accept(SearchedCaseExpression.java:48)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:198)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:687)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:180)
        at com.facebook.presto.sql.tree.Cast.accept(Cast.java:61)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:198)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:621)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:180)
        at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:70)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:177)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:970)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeExpression(TupleAnalyzer.java:1066)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeSelect(TupleAnalyzer.java:869)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:348)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:133)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:99)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:493)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:114)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:81)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitTableSubquery(TupleAnalyzer.java:329)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitTableSubquery(TupleAnalyzer.java:133)
        at com.facebook.presto.sql.tree.TableSubquery.accept(TableSubquery.java:36)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeFrom(TupleAnalyzer.java:918)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:344)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:133)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:99)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:493)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:114)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:81)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitShowPartitions(StatementAnalyzer.java:294)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitShowPartitions(StatementAnalyzer.java:114)
        at com.facebook.presto.sql.tree.ShowPartitions.accept(ShowPartitions.java:64)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:208)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:193)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:154)
        at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QuerySubmitter$2.run(SqlQueryManager.java:470)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

### CODE REVIEW

**Comment by martint** [comment]
Thanks! Can you add a null check to SearchedCaseExpression's constructor and a test case to TestSqlParser?

**Comment by martint** [comment]
Oh, actually, since it's not a parser issue add the test to TestAnalyzer

**Comment by martint** [comment]
Ugh, nevermind... adding a test like that is not going to be easy since it requires a bunch of other stuff to be set up (information_schema, etc). Just add the null check...

**Comment by nezihyigitbasi** [comment]
Yep, I was trying to add that and miserably failing. Will update the PR shortly.

**Comment by nezihyigitbasi** [comment]
@martint I was just adding more tests for ``show partitions`` to ``TestSqlParser``. Will put those in a separate commit.

**Comment by nezihyigitbasi** [comment]
@martint updated with more parser tests.

**Comment by martint** [comment]
Merged with minor formatting changes. Thanks!

**Pull request closed without merging**
