### PR TITLE
Change hive default storage format to ORC

### PR DESCRIPTION
**Pull request by yuananf**

### CODE REVIEW

**Comment by electrum** [comment]
We need to benchmark this. I think that rcbinary is much faster to write. We should also get zlib compression automatically with rcbinary, but I think ORC doesn't compress without additional flags.

**Comment by cberner** [comment]
We also need to think about how much memory the orc writer uses. Right now, the memory manager doesn't track the memory usage of the table writer operator, which is fine for rcbinary because it's minimal (I think). If orc is significant though, we might need to track that to avoid OOMs

**Comment by yuananf** [comment]
I see. So we should fully test the ORC write efficiency, before changing default storage format to ORC.

**Comment by dain** [comment]
@electrum the default compression with ORC is zlib

**Comment by dain** [comment]
I'm going to close this for now.  When we have a custom (fast) ORC writer, we will switch the format.

**Pull request closed without merging**
