### PR TITLE
Fix race condition in TestPrioritizedFifoExecutor

### PR DESCRIPTION
**Pull request by cberner**
Also make a couple improvements to the Travis build

### CODE REVIEW

**Comment by electrum** [comment]
Good catch! I think it would be better to wait for the last future by calling get().

**Comment by cberner** [comment]
Oh ya, that's much cleaner. Updated.

**Comment by electrum** [comment]
I don't think these tests should be single threaded. They definitely should not need to be, so this seems to be papering over either a real problem or a problem with the tests.

**Comment by electrum** [comment]
Also, while not being real concurrency tests, being multithreaded might happen to catch concurrency issues in the code.

**Comment by electrum** [comment]
Remove the last two commits that make the tests single threaded. I'll see if I can figure out why they fail now that you found how to reproduce by setting the thread count very high. Others look good.

**Pull request merged**
