### PR TITLE
Refactor ParquetHiveRecordCursor

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
This PR cleans up the ParquetHiveRecordCursor.

### CODE REVIEW

**Comment by cberner** [comment]
How does this relate to #2981?

**Comment by zhenxiao** [comment]
@cberner @dain this is not related to https://github.com/facebook/presto/pull/2981
This is @nezihyigitbasi 's work refactoring and cleaning the ParquetHiveRecordCursor, https://github.com/facebook/presto/pull/2981 is my hacking work about new Parquet Reader, which is using PageSource api, not RecordCursor api.

**Comment by dain** [comment]
Merged, thanks!

**Comment by dain** [comment]
I rebased and squashed the commits.

**Pull request closed without merging**
