### PR TITLE
New Parquet Reader

### PR DESCRIPTION
**Pull request by zhenxiao**

### CODE REVIEW

**Comment by snarayananqubole** [comment]
Awesome @zhenxiao ! Do you have any perf comparisons with the old reader?

**Comment by zhenxiao** [comment]
@snarayananqubole I did some benchmarking, on an 8 node cluster, the whole dataset is ~100GB, all queries are selecting the same columns, I vary the predicate selectivity(time in seconds, the benchmark ran 5 times and take the average):
parquet

For selective queries, new reader is much faster, as it only reads the footer and skip reading row groups. For not-selective queries, new reader performs similar to old reader.

Now this PR has vectorization and predicate pushdown(row group filter), it is self contained, so I sent for review.

Complex types are not supported, which I will continue work on, also will add lazy vector, which could make parquet performs better.

**Comment by snarayananqubole** [comment]
@zhenxiao Thanks!

**Comment by zhenxiao** [comment]
@cberner @dain This PR is not related to https://github.com/facebook/presto/pull/2947, this is a new Parquet Reader, implementing PageSouce, not using RecordCursor. It is still work in progress, now it has vectorized read and predicate pushdown, I will add lazy vector.

**Comment by zhenxiao** [comment]
@cberner @dain @snarayananqubole 
Need more work to make it stable and calling the ParquetVectorizedReader apis. Let me close it for now, and will resubmit when it is ready.
The code will still be on my branch, just not a public PR. comments and suggestions are appreciated.

**Pull request closed without merging**
