### PR TITLE
Rename max split iterator threads parameter

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
@electrum This PR is for renaming the ``hive.max-global-split-iterator-threads`` parameter to
``hive.max-split-iterator-threads``.

### CODE REVIEW

**Comment by yan-stein** [comment]
Could you please share the motivation behind this change?  Thank you.

**Comment by nezihyigitbasi** [comment]
@yan-stein Previously the ``hive.max-split-iterator-threads`` parameter was unused and we removed it (see #2840) and the only parameter that controls the max split threads is ``hive.max-global-split-iterator-threads`` and its name has ``global`` in it, which I think is confusing. The motive is to just simplify its name as ``global`` doesn't tell much to the user.

**Comment by yan-stein** [comment]
@nezihyigitbasi Thank you for your explanation and the reference!

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request closed without merging**
