### PR TITLE
Remove duplicate DistinctLimitNode from query plan

### LINKED ISSUE #3646: Duplicate DistinctLimitNode in query plan
When explain distinct limit query, the plan looks like below
There are duplicate DistinctLimit in the plan.
```
presto:orc> explain select distinct l_orderkey from lineitem limit 10;
                                                                                Query Plan                                                                                 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[l_orderkey] => [l_orderkey:bigint]                                                                                                                               
     - DistinctLimit[10] => [l_orderkey:bigint, $hashvalue:bigint]                                                                                                         
         - Exchange[GATHER] => l_orderkey:bigint, $hashvalue:bigint                                                                                                        
             - DistinctLimit[10] => [l_orderkey:bigint, $hashvalue:bigint]                                                                                                 
                 - DistinctLimit[10] => [l_orderkey:bigint, $hashvalue:bigint]                                                                                             
                     - Project => [l_orderkey:bigint, $hashvalue:bigint]                                                                                                   
                             $hashvalue := "combine_hash"(0, COALESCE("$operator$hash_code"("l_orderkey"), 0))                                                             
                         - TableScan[hive:hive:orc:lineitem, originalConstraint = true] => [l_orderkey:bigint]                                                             
                                 LAYOUT: hive                                                                                                                              
                                 l_orderkey := HiveColumnHandle{clientId=hive, name=l_orderkey, ordinalPosition=0, hiveType=bigint, hiveColumnIndex=0, partitionKey=false}
```

### PR DESCRIPTION
**Pull request by raghavsethi**
Fixes #3646

### CODE REVIEW

**Comment by martint** [comment]
looks good

**Comment by erichwang** [comment]
Hm, I think we might actually need the distinct limit in this case?

**Comment by raghavsethi** [comment]
The root node is still a DistinctLimitNode, so there is still a DistinctLimit on both sides of the Exchange. The query plan post this fix looks correct:
```
 - Output[orderkey] => [orderkey:bigint]
     - DistinctLimit[10] => [orderkey:bigint, $hashvalue:bigint]
         - Exchange[GATHER] => orderkey:bigint, $hashvalue:bigint
             - DistinctLimit[10] => [orderkey:bigint, $hashvalue:bigint]
                 - Project => [orderkey:bigint, $hashvalue:bigint]
                         $hashvalue := "combine_hash"(0, COALESCE("$operator$hash_code"("orderkey"), 0))
                     - TableScan[tpch:tpch:lineitem:sf0.01, originalConstraint = true] => [orderkey:bigint]
                             orderkey := tpch:orderkey
```

**Comment by erichwang** [comment]
ah got it. looks good

**Pull request merged**
