### PR TITLE
Skip checks for presto-server-rpm module

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by dain** [comment]
looks good

**Comment by cawallin** [comment]
Thanks for this fix and the newline fix. Are there any tests that were failing because of this (that we can make sure to run), and is there anywhere in addition to airlift/codestyle that we should look so we don't overlook things like this?

**Comment by electrum** [comment]
The duplicate checker failed in our Jenkins CI when the whole project is built. I couldn't reproduce when just building that module. For the newlines, that is just something I noticed manually.

**Comment by electrum** [comment]
I think checkstyle does check for newlines, but we only run it on Java source, so it doesn't work for other types of files. Also, when you do a diff in Git, it will show an error about missing newlines.
```
git show 8fe9db917e92b00a18dcbb3321207309d1390abe
...
diff --git a/presto-server-rpm/src/main/resources/dist/config/jvm.config b/presto-server-rpm/src/main/resources/dist/config/jvm.config
new file mode 100644
...
+-XX:+UseGCOverheadLimit
+-XX:OnOutOfMemoryError=kill -9 %p
\ No newline at end of file

**Pull request closed without merging**
