### PR TITLE
Extract AbstractTestFunctions

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by martint** [comment]
Does functionAssertions even need to be an instantiatable class (instead of static methods)? I dislike being forced to use inheritance for code reuse

**Comment by electrum** [comment]
Yes, it needs to be able to take a different session. That is used by some of the datetime function tests.

**Comment by electrum** [comment]
They also have some expensive state which is why we only instantiate them once per class. We could consider having some static methods that use a single static instance. @dain might have an opinion about that.

**Comment by dain** [comment]
looks good

**Pull request merged**
