### PR TITLE
Revert to older version of jetty

### PR DESCRIPTION
**Pull request by nileema**

### CODE REVIEW

**Comment by cberner** [comment]
looks good

**Comment by xerial** [comment]
Just out of curiosity. Is there any problem in the latest version of jetty?

**Comment by cberner** [comment]
We've been chasing down a connection pool leak in Jetty, and it seemed to be worse when using the latest version. They're working on a new version that should allow us to upgrade again.

**Comment by xerial** [comment]
That's good to know. Thanks.

**Comment by electrum** [comment]
Note that this is the Jetty client, not the server.

**Pull request merged**
