### PR TITLE
Make TupleDomain type generic

### PR DESCRIPTION
**Pull request by erichwang**

### CODE REVIEW

**Comment by haozhun** [comment]
Doing the first pass:
Add Block JSON serde: looks good
Add stack value methods to Block and BlockBuilder: looks good. But I don't know whether this code should better be living in a utility class or in `Block` and `BlockBuilder`.
New TupleDomain format: still looking

**Comment by haozhun** [comment]
Add Block JSON serde: Looks good.
Add stack value methods to Block and BlockBuilder: I prefer that this code live in a utility class instead of `Block` and `BlockBuilder`.
New TupleDomain format: See comments.
The other 7 commits: I skimmed through them because the changes are mostly mechanical. Looks good. One concern though, a lot of intermediate commits here don't compile. Is this okay? Should they be squashed before merge?

@martint It's your turn.

**Comment by erichwang** [comment]
Yes i will squash before commit, this is just so that it is easier to read.

**Comment by martint** [comment]
Make sure you validate this with the verifier and Hive integration tests.

I'm still not convinced about the requirement that each set type must operate against the same set type, but we can leave that for future consideration.

Other than those comments, it looks good.

**Pull request merged**
