### PR TITLE
fields_length property in blackhole connector

### PR DESCRIPTION
**Pull request by pnowojski**
fields_length property in blackhole connector

Added fields_length table property to blackhole connector, which overwrites default length of returned VARBINARY and VARCHAR columns.

Reviewers: arosa

### CODE REVIEW

**Comment by arhimondr** [comment]
lgtm

**Comment by electrum** [comment]
Name this singular: field_length

**Comment by pnowojski** [comment]
@electrum, isn't the plural better since it applies to all fields/columns of varchar or varbinary type?

**Comment by electrum** [comment]
@pnowojski, it applies to every field, but it is the limit for each field (a specific field, i.e. one field).

If we had a property for the maximum size of a row, it would be called "max row size" because it is applied for each row.

**Comment by pnowojski** [comment]
@electrum ok, fixed

**Comment by pnowojski** [comment]
@electrum  Done

**Comment by martint** [comment]
Unit tests are failing with:

```
java.lang.NullPointerException
	at com.facebook.presto.plugin.blackhole.BlackHoleMetadata.beginCreateTable(BlackHoleMetadata.java:153)
	at com.facebook.presto.plugin.blackhole.BlackHoleMetadataTest.tableIsCreatedAfterCommits(BlackHoleMetadataTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by pnowojski** [comment]
Ops, I don't know why I have missed it. Fixed

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
