### PR TITLE
Implement metadata delete for Hive

### PR DESCRIPTION
**Pull request by haozhun**
Depend on #3377

### CODE REVIEW

**Comment by cberner** [comment]
back to you for comments

**Comment by haozhun** [comment]
For `HiveMetadata.metadataDelete` line 1214, @cberner commented
> this looks correct to me, but have Martin or Eric look at this method

@martint @erichwang 

For `ConnectorMetadata.canDoMetadataDelete`, @cberner commented
> should this also take a layout/predicate? it seems like some connectors might only be able to do metadata deletes for specific columns. In fact, doesn't Hive need that, since it can only do a metadata delete on partition columns?

I only added the arguments that I needed. I understand that this is SPI and the general principal of adding only things needed doesn't necessarily apply. Anyways, I'm still concerned that the sole reason of adding a argument is because we think someone might need it in the future. But I'll let you make the decision.

For `MetadataDeleteNode.MetadataDeleteNode`, @cberner commented
> it looks like the operator only outputs a single channel, so this should be a single Symbol instead of a List

`TableCommitNode` also take a list. Given `getOutputSymbols` have to return `List<Symbol>`, I'm not sure whether taking a single Symbol is a good idea.

For `TestHiveIntegrationSmokeTest.testMetadataDelete`, @cberner commented
> add a test for a non-metadata-only-delete to make sure it fails with a reasonable error message

I guess `This connector does not support deletes` is not considered reasonble? What do you recommend?

**Comment by cberner** [comment]
Re "ConnectorMetadata.canDoMetadataDelete": My point was that even for Hive it seems like you need more information to know if you can do a metadata only delete. For example, if I delete "WHERE userid = 1" (and assuming that's not a partition) that's not something that can be processed as a metadata delete.

I'd say that `TableCommitNode` is implemented poorly as well then :) The reason I think a single `Symbol` is better is that it reflects the fact that the node outputs a single `Symbol` and would catch any programming errors in the future where multiple symbols were passed in

`"This connector does not support deletes"` seems fine as the default message. I meant for the Hive connector specifically. It should have a better message like `DELETE predicate must specify an entire partition`. If it's available when you print that error, I would add the partition columns like ` (partition columns for "my_table" are [ds, type])`

**Comment by electrum** [comment]
Nit: I dislike the name `canDo`. How about `supports`

**Comment by cberner** [comment]
Looks good, but see comments

**Comment by haozhun** [comment]
MetadataDeleteOptimizer:88
> Looks like the last part of this comment about exchanges doesn't apply? I don't see any handling of exchanges here

It applies.

---

MetadataDeleteNode:47
> Add a checkArgument that the size of outputs is 1

Sorry. Should have fixed this by making outputSymbol not a list.

---

HiveColumnHandle:163
> Not sure if it matters, but should the last argument really be true? It seems like this wouldn't be a partition key

We've talked. Let's reach a conclusion tomorrow.

---

HiveTableLayoutHandle:80
> Move `getOrComputePartitions`

Let's talk.

---

HiveTableLayoutHandle:87
> pass `Optional.empty()` for the desired columns

Let's talk.

**Pull request merged**
