### PR TITLE
Convert type to appropriate hive type when adding a new column

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
This PR converts a column's type to the appropriate Hive type for `alter table` statements.

### CODE REVIEW

**Comment by martint** [comment]
Can you add an explanation to the commit message of what/how it was broken, what problem it caused, etc?

**Comment by nezihyigitbasi** [comment]
@martint sorry I forgot that, will add it shortly. The issue was reported in the mailing list today, please see [this post](https://groups.google.com/forum/#!topic/presto-users/Bap6X6nP9Tw).

**Comment by nezihyigitbasi** [comment]
@martint updated the commit message.

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
