### PR TITLE
Add session property task_max_memory

### PR DESCRIPTION
**Pull request by yuananf**
this session property is equivalent to task.max-memory

usage:
set session task_max_memory='1GB';
set session task_max_memory='256MB';
reset session task_max_memory;

### CODE REVIEW

**Comment by dain** [comment]
@cberner do we need this with the new memory manager in #2873?

**Comment by cberner** [comment]
Probably not. My plan was to remove the task limit, and instead you would set the per-query-per-node limit. This also isn't a safe session property to add, as users could set the limit arbitrarily high. I think if we're going to add this it should return the minimum of the default (config) value and the session value

**Comment by yuananf** [comment]
It will be good to be able to set per-query-per-node limit.
Because there are various queries(maybe very big) in our cluster, and we can not decide what is the proper value of this property, so we have to set task.max-memory quite high to avoid OOM failure.

**Comment by cberner** [comment]
@yuananf yep, we face the same issue. I'd rather not merge this, since "task.max-memory" is being replaced by the "query.max-memory" and "query.max-memory-per-node" configs, but feel free to add session properties for those configs! Or if you really need this, please re-open and I'll take another look.

**Comment by yuananf** [comment]
Thanks, I'll have a look at the new configs.

**Pull request closed without merging**
