### PR TITLE
Optimize map_agg memory usage.

### LINKED ISSUE #2788: Optimize memory usage of map_agg
`map_agg` relies on `KeyValuePairs` which always allocates a full `PageBuilder` this is very wasteful, as you may only be aggregating a few values into the map. We need to fix the TODO in `KeyValuePairs` to create an optimized version of `GroupByHash` that uses less memory

### PR DESCRIPTION
**Pull request by yaoxin226**
Fix #2788 
Replace GroupByHash with a new class TypedSet to reduce memory useage.

### CODE REVIEW

**Comment by yaoxin226** [comment]
Hi @cberner , could you take a look when you have time? Thanks.

**Comment by yaoxin226** [comment]
Current master(04ad885fd7) also failed build on my Mac with the same Error.
```bash
$> mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q -T 2
...
[ERROR] /Users/xin.yao/Github/yaoxin226-presto/presto-main/src/main/java/com/facebook/presto/concurrent/FairBatchExecutor$PrioritizedFutureTask.java:195: Prefer java.lang.Long.compare(long, long)
[ERROR] /Users/xin.yao/Github/yaoxin226-presto/presto-main/src/main/java/com/facebook/presto/connector/jmx/JmxMetadata$1.java:-1: Prefer java.util.function.Predicate
[ERROR] /Users/xin.yao/Github/yaoxin226-presto/presto-main/src/main/java/com/facebook/presto/execution/NodeScheduler$1.java:-1: Prefer java.util.function.Supplier
...
```
Should we fix these "Prefer" check?

**Comment by cberner** [comment]
Made a couple minor modifications and put this up in https://github.com/facebook/presto/pull/2892 should be merged soon. Thanks!

**Comment by cberner** [comment]
Merged. Thanks!

**Comment by yaoxin226** [comment]
Thanks for the review.

**Comment by yaoxin226** [comment]
Made a minor PR #2899  to update the access level to member of SImpleTypedSet

**Pull request closed without merging**
