### PR TITLE
Optimize constant window function partitions

### PR DESCRIPTION
**Pull request by zhenxiao**
Fix https://github.com/facebook/presto/issues/2458

### CODE REVIEW

**Comment by cberner** [comment]
Could you rebase on master and see if that fixes the Travis tests?

**Comment by zhenxiao** [comment]
@cberner thank you, get it rebased

**Comment by zhenxiao** [comment]
@erichwang kindly ping

**Comment by erichwang** [comment]
@zhenxiao, this ideally should be in an optimizer since we would want to do this optimization not only if the partition is a Literal, but also if it is effectively constant due to constant folding, or other known properties. Right now this information is only available in the AddExchanges optimizer, but we will need to split that apart into smaller pieces first since it is doing quite a lot right now. In the meantime, could we hold off on this optimization?

**Comment by zhenxiao** [comment]
@erichwang Get it. Sure. Would you please ping me when you think it is a good time to continue?

**Comment by martint** [comment]
Closing, since the final solution requires a different approach.

**Pull request closed without merging**
