### PR TITLE
Fix negative caching for Hive metadata

### LINKED ISSUE #1540: Fix negative caching for Hive metadata
Background refresh doesn't handle the case where a table is dropped. The lookup throws an exception because the table does not exist, but this won't clear the entry from the cache. Adding negative caching by having the cache store `Optional` will fix this (though we should probably bound the cache size when adding that).

### PR DESCRIPTION
**Pull request by electrum**
Fixes #1540

### CODE REVIEW

**Comment by dain** [comment]
looks good

**Comment by alexingcool** [comment]
@electrum I still found a problem. If you create a table in hive, first show tables can't get the table, and you must show tables twice. Maybe this problem is also caused by cache.
Description:
1: Create a table in hive, maybe named test;
2. Show tables in Presto,  the test table is not appeared
3. Show tables in Presto again, then the test table appeared
This table also exists in drop table.

**Comment by dain** [comment]
@alexingcool, that is expected behavior.  If you need that level of consistency, you will need to disable the cache in Presto.  We run with the cache at FB because our metastore is not reliable (or performant) enough for interactive users.

**Comment by alexingcool** [comment]
@dain electrum use 'Optional' to label whether the item cached is empty or not, so one second refresh interval already let the cache know what happened in metastore. Is this behavior caused by CacheBuilder? return an old value immediately and the get a refresh.
Once, I was curios about this cache mechanism. Now I know why you do this. I don't know whether disable cache will affect online tasks, but I can show tabls or partitions before select to get a refresh.

**Pull request closed without merging**
