### PR TITLE
Fix Hive partition column validation

### PR DESCRIPTION
**Pull request by raghavsethi**
The previous approach to validation presented the user with a
difficult to understand error message and made one code path
unreachable.

### CODE REVIEW

**Comment by haozhun** [comment]
* Checkstyle failure
* Add tests for these 3 types of failures in TestHiveIntegrationSmokeTest.

**Comment by raghavsethi** [comment]
On it

**Comment by raghavsethi** [comment]
@haozhun ready for review pending a test run passing.

**Comment by raghavsethi** [comment]
I'd already added tests for the invalid ordering case.

**Comment by haozhun** [comment]
Looks good. Assuming Travis passes.

**Pull request merged**
