### PR TITLE
Only support per-host configuration for S3

### PR DESCRIPTION
**Pull request by zhenxiao**
follow https://github.com/facebook/presto/commit/17c50700f4b117e995f5e954e8759bd16b0a8460

### CODE REVIEW

**Comment by dain** [comment]
I think @electrum fixed this the other day

**Comment by electrum** [comment]
Do you need this for S3? I actually removed it because it isn't needed for file systems like S3.

**Comment by zhenxiao** [comment]
@electrum @dain oh, a number of s3 configurations are in HdfsConfigurationUpdater, eg.
config.set("fs.s3.impl", PrestoS3FileSystem.class.getName());

The naming, HdfsConfigurationUpdater is not so good. It sets the FileSystem implementation and all s3 specific configs there.
I happened to see Hadoop's NativeS3FileSystem call stack when trying the current master.

**Comment by nezihyigitbasi** [comment]
@electrum This is needed because s3 file system impl. is set in the HdfsConfigurationUpdater, so without this patch we can't query tables on s3. We get the exception below that shows ``org.apache.hadoop.fs.s3native.NativeS3FileSystem`` is used instead of the PrestoS3Filesystem.

```
Caused by: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3n URL, or by setting the fs.s3n.awsAccessKeyId or fs.s3n.awsSecretAccessKey properties (respectively).
        at org.apache.hadoop.fs.s3.S3Credentials.initialize(S3Credentials.java:70)
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.initialize(Jets3tNativeFileSystemStore.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:186)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at org.apache.hadoop.fs.s3native.$Proxy136.initialize(Unknown Source)
        at org.apache.hadoop.fs.s3native.NativeS3FileSystem.initialize(NativeS3FileSystem.java:272)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:74)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:61)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:43)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:367)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:287)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:62)
        at com.facebook.presto.hive.HiveSplitSourceProvider.loadPartitionSplits(HiveSplitSourceProvider.java:231)
        at com.facebook.presto.hive.HiveSplitSourceProvider.access$100(HiveSplitSourceProvider.java:84)
        at com.facebook.presto.hive.HiveSplitSourceProvider$2.run(HiveSplitSourceProvider.java:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at io.airlift.concurrent.BoundedExecutor.executeOrMerge(BoundedExecutor.java:69)
        at io.airlift.concurrent.BoundedExecutor.access$000(BoundedExecutor.java:28)
        at io.airlift.concurrent.BoundedExecutor$1.run(BoundedExecutor.java:40)
        ... 3 more
```

**Comment by electrum** [comment]
Thanks for the explanation. You're right, the way that code is put together is confusing. I simplified it by getting rid of the scheme handling in #2744.

**Pull request closed without merging**
