### PR TITLE
Add element_at function for Array.

### PR DESCRIPTION
**Pull request by yaoxin226**
Supports access element both from beginning and end.

Take @electrum 's suggestion in #2790 , add a function to support access array element from the end.

### CODE REVIEW

**Comment by electrum** [comment]
Thanks for sending this. We will discuss the function name. One alternative idea is to implement the ``reverse`` function for arrays and add an optimizer for this specific expression type:

```
array_get(a, -1)
```
vs
```
reverse(a)[-1]
```

**Comment by yaoxin226** [comment]
Thanks for your reply.
Another expression with an additional optimizer
```
a[cardinality(a)]
```

reverse(a)[1] and a[cardinality(a)]   vs  array_get
* reverse(a)[1] and a[cardinality(a)]
  * good for reducing the total number of function by only keeping the basic functions. And compose these functions to achieve complex functionality. 
  * It isn't easy for user to know the performance is also good, there will be a optimizer to optimize this expression.
* array_get
  * will bring a burden for user to remember a new function. And introduced a new way to express the same thing( array_get(a, -1) vs a[cardinality(a)] ). 
  * But the bright side is, user can immediately know array_get has the best performance just from function name.

**Comment by electrum** [comment]
Good points. An additional downside of the cardinality is that it requires repeating the array expression (which could be long and possibly non-deterministic) and for non-last cases requires even more typing for subtraction.

**Comment by yaoxin226** [comment]
Any updates?

**Comment by cberner** [comment]
@martint and @electrum are discussing how to name this method. It seems like the right approach though

**Comment by yaoxin226** [comment]
@cberner Thanks for sharing the progress.

**Comment by martint** [comment]
My thought is that we should name it in a way that's not specific to arrays. If expect that in the future we'll have a similar function for any type that is indexable (VARCHAR, VARBINARY, etc), so something like `element_at` would be more appropriate (other options: `get_item`, `get_entry`, `get_element`).

**Comment by yaoxin226** [comment]
Thanks @martint for your feedback.

`element_at` sounds great to me, since we already using the term **element** in docs of array functions.
Can we finalize the function signature to `element_at(array<E>, index) -> E`, then I will update the code accordingly.

**Comment by martint** [comment]
@yaoxin226 yeah, that looks good

**Comment by yaoxin226** [comment]
This RP is ready to be reviewed.

**Comment by yaoxin226** [comment]
Rebased on latest master

**Comment by yaoxin226** [comment]
ping

**Comment by cberner** [comment]
I'll review this, but have a few other things I need to review first

**Comment by cberner** [comment]
Looks good. I plan to merge this for the 0.113 release

**Comment by yaoxin226** [comment]
Awesome! Thanks for the review.

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request closed without merging**
