### PR TITLE
Specify SERDE for CREATE TABLE

### PR DESCRIPTION
**Pull request by losipiuk**
Replacement for https://github.com/TeradataCenterForHadoop/presto-td/pull/12

### CODE REVIEW

**Comment by electrum** [comment]
Can you rebase this so it doesn't have the insert code?

**Comment by losipiuk** [comment]
Do you mean to rebase this patch on top of PR #2574 ?
I cannot do that. This PR depends on support for CREATE TABLE, and #2574 is lagging behind master too much.

**Comment by electrum** [comment]
I mean rebase on master, but remove the insert commit.

**Comment by losipiuk** [comment]
But I cannot do that until the insert pull request is merged into master. Right? This PR depends on INSERT code.

**Comment by electrum** [comment]
Ah, I see. In that case we will wait until Dain is finished with that one. Thanks for explaining.

**Comment by martint** [comment]
@losipiuk, the INSERT code is in now. Can you rebase this?

**Comment by dain** [comment]
I thought we decided we didn't need this one.

On Oct 9, 2015, at 1:09 PM, Martin Traverso <notifications@github.com>
wrote:

@losipiuk <https://github.com/losipiuk>, the INSERT code is in now. Can you
rebase this?

—
Reply to this email directly or view it on GitHub
<https://github.com/facebook/presto/pull/3093#issuecomment-146975418>.

**Pull request closed without merging**
