### PR TITLE
add WITH ORDINALITY support to UNNEST

### PR DESCRIPTION
**Pull request by haozhun**
Issue #2504

### CODE REVIEW

**Comment by haozhun** [comment]
Depends on #2536

**Comment by cberner** [comment]
Back to you for comments

**Comment by haozhun** [comment]
Fixed issues mentioned in your comments. Ready for review again.

**Comment by haozhun** [comment]
Added tests after comments from @martint (which disappeared). Ready for review again.

**Comment by cberner** [comment]
looks good

**Comment by haozhun** [comment]
merged

**Pull request closed without merging**
