### PR TITLE
Use display name for serializing types

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by electrum** [comment]
There is a commented out test for parsing row types because the parsing is broken. I'm not sure if we should fix the display name or the parser.

**Comment by dain** [comment]
Other than this possible outstanding issue with row types not parsing correctly, it looks good to me, but I think @martint should review this.

**Comment by cberner** [comment]
What's the motivation for this? Relying on the display name sounds like a bad idea to me, as it's for human consumption, not parsing

**Comment by electrum** [comment]
See #4532

I'm thinking we should actually have a new method on Type to get the serialized string. Then we can just fix varchar and not affect other types (unless they also need custom handling).

**Comment by dain** [comment]
@cberner the problem is the new VARCHAR length code prints VARCHAR(2147483648) for VARCHAR without length, but that isn't the actual type and is a side effect of the internal representation of the type.  This creates problems for systems that store this value (like raptor).

**Comment by cberner** [comment]
What's the difference between the "internal" and the "actual" type? I haven't looked at any of the new varchar code, but relying on the display name doesn't seem like a good way to do serialization

**Comment by electrum** [comment]
I agree, we need something better. Suggestions appreciated.

**Comment by electrum** [comment]
Replaced by #4537

**Pull request closed without merging**
