### PR TITLE
Benchmark driver fix

### PR DESCRIPTION
**Pull request by mvp**
Added some fixes for benchmark driver:

Support skipping failed queries, and capture error messages if any
Sort list of files for benchmark driver

### CODE REVIEW

**Comment by electrum** [comment]
Please start commit messages with a capital letter and follow the standard format: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

The second commit message is too long and doesn't need a comma.

**Comment by electrum** [comment]
Can shorten to "Support skipping failed queries and capture error messages"

**Comment by mvp** [comment]
David, fixed issues you mentioned. Also, added custom exception type BenchmarkDriverExecutionException to make it clear when we deal with failed queries.

**Comment by dain** [comment]
Let me know when the changes are integrated

**Comment by dain** [comment]
Merged

**Comment by dain** [comment]
Merged

**Pull request closed without merging**
