### PR TITLE
Fix bug in CountConstantOptimizer and add test

### LINKED ISSUE #3839: Is CountConstantOptimizer broken?
I saw https://github.com/facebook/presto/pull/1516, but when I tried I got the following result:
```
presto:orc> EXPLAIN SELECT COUNT(42) FROM ORDERS;
                                       Query Plan                                       
----------------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]                                                      
         _col0 := count                                                                 
     - Aggregate(FINAL) => [count:bigint]                                               
             count := "count"("count_3")                                                
         - Exchange[GATHER] => count_3:bigint                                           
             - Aggregate(PARTIAL) => [count_3:bigint]                                   
                     count_3 := "count"("expr")                                         
                 - Project => [expr:bigint]                                             
                         expr := 42                                                     
                     - TableScan[hive:hive:orc:orders, originalConstraint = true] => [] 
                             LAYOUT: hive
```
So it seems this optimizer is not working, correct me if I am wrong.
@dain @martint @erichwang

### PR DESCRIPTION
**Pull request by raghavsethi**
Fixes #3839

### CODE REVIEW

**Comment by martint** [comment]
This needs a better commit message. What's the bug (observed behavior)? How does this fix it?

**Comment by raghavsethi** [comment]
@haozhun made the changes you requested in the test.

**Comment by haozhun** [comment]
@erichwang This looks good to me. Do you want to take a look?

**Comment by erichwang** [comment]
looks good

**Comment by raghavsethi** [comment]
@haozhun please merge after the release.

**Pull request merged**
