### PR TITLE
Use Map.getOrDefault at NodeScheduler

### PR DESCRIPTION
**Pull request by miniway**
`getOrDefault` could simplify some lines at `NodeScheduler`.

### CODE REVIEW

**Comment by electrum** [comment]
Typo in commit message "schduler"

**Comment by electrum** [comment]
Sorry, I misread the Pull Request title as the commit message.

**Comment by miniway** [comment]
Sorry for my hastiness. Typo is my destiny sigh...

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
