### PR TITLE
Add shard size constraints to Raptor

### PR DESCRIPTION
**Pull request by nileema**

### CODE REVIEW

**Comment by damiencarol** [comment]
I want to understand, what is shard size constraint ?

**Comment by nileema** [comment]
Currently we determine how much data goes into a shard based on row count, we want to make a decision based on row count and data size in bytes.

**Comment by damiencarol** [comment]
Thanks for the clarifications. I saw the details on commits. Code is enough clear and understandable.

**Comment by electrum** [comment]
Looks good

**Pull request merged**
