### PR TITLE
Decimal v5

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by losipiuk** [comment]
This PR supersedes https://github.com/facebook/presto/issues/4426

**Comment by damiencarol** [comment]
Innovation !
5price1

**Comment by tomz** [comment]
Would like to try this out, can the merge conflicts be resolved?

**Comment by losipiuk** [comment]
Superseded by https://github.com/facebook/presto/pull/4750

**Comment by arhimondr** [comment]
@martint all your and @dain 's comments have been addressed. We are looking forward to get this merged. If you had any other minor comments i would like to address them today.

**Pull request closed without merging**
