### PR TITLE
Explain DropTable, DropView, and RenameTable

### PR DESCRIPTION
**Pull request by zhenxiao**
Fix NullPointerException when trying to EXPLAIN RENAME or EXPLAIN DROP
https://github.com/facebook/presto/issues/1812

### CODE REVIEW

**Comment by zhenxiao** [comment]
@martint code rebased, also add explain create table

**Comment by zhenxiao** [comment]
@cberner @martint kindly ping

**Comment by electrum** [comment]
I think this is the wrong approach. Instead, we should be able to inject `Map<Class<? extends Statement>, DataDefinitionTask<?>> tasks` into `QueryExplainer` (same as `DataDefinitionExecutionFactory`), then call `getName()` on the task.

This could be improved later to have an `explain()` method that takes the `Statement`, allowing it to show `RENAME TABLE foo TO bar` rather than just `RENAME TABLE`, but let's start with `getName()`.

**Comment by zhenxiao** [comment]
@electrum get it. Thanks for your comment. I will do it

**Comment by zhenxiao** [comment]
@electrum do you mean make QueryExplainer an interface, and having a factory to create query explain execution for DataDefinition and Query?

**Comment by electrum** [comment]
Ah, yeah, the way `QueryExplainer` is used makes this more difficult. This might take some refactoring. Would need to play around with it.

**Comment by dain** [comment]
Superseded by #3524

**Pull request closed without merging**
