### PR TITLE
Add additional unit tests for the Histogram function

### PR DESCRIPTION
**Pull request by mattsfuller**
Test with both null and non null input for the Histogram aggregate
function. Also test with only null input.

### CODE REVIEW

**Comment by mattsfuller** [comment]
@petroav can you review

**Comment by mattsfuller** [comment]
The tests pass locally for me. It might be an intermittent issue with the test that's failing.

**Comment by petroav** [comment]
Looks good

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
