### PR TITLE
Do not constant fold failures in conditional expressions

### PR DESCRIPTION
**Pull request by nileema**
Failures are constant folded to FailureFunction with UNKNOWN type
This causes the failure function to be replaced by NULL in the
ExpressionOptimizer, causing incorrect results. Leave the failed
expression as is and constant fold all other expressions

### CODE REVIEW

**Comment by haozhun** [comment]
I don't understand why you chose to remove many of the tests. Other than that, the code seems good to me.

But I think it's worth discussing this change with @dain, @martint and see what they think.

**Comment by nileema** [comment]
I removed those because it is already tested elsewhere. We'd added those just to test that the ``fail()`` is generated correctly.

**Comment by dain** [comment]
looks good

**Comment by nileema** [comment]
Merged

**Pull request closed without merging**
