### PR TITLE
Optimize SearchedCase expression on constant

### PR DESCRIPTION
**Pull request by yaoxin226**
Optimize SearchedCase expression on constant
  * Remove the WhenClauses whose operand is FALSE
  * If we find a WhenClause, whose operand is TRUE, remove all the WhenClauses on its right and the default value.

### CODE REVIEW

**Comment by yuananf** [comment]
There are tests failures.

**Comment by yaoxin226** [comment]
Thanks @yuananf , it should be fixed by commit  dfa7119

**Comment by cberner** [comment]
Just talked to @martint about this, and there's a better way to do this. He's moving everything over to the new `RowExpression` framework, so optimizations should now be added to `ExpressionOptimizer.java`. In that framework `CASE` is converted to `SWITCH`. Let me know if you have questions about how to implement it there

**Comment by yaoxin226** [comment]
Superseded by #3354

**Pull request closed without merging**
