### PR TITLE
Fix to speedup ORC with S3

### PR DESCRIPTION
**Pull request by stagraqubole**
This is the fix for the problem described in this mail thread:
https://groups.google.com/d/msg/presto-users/VBKKTYw-nOg/Dqc2Bd9iAIAJ

When HdfsOrcDataSource.readFully is called, this method in FSInputStream gets called in a loop till all the data is read:
```java
public int read(long position, byte[] buffer, int offset, int length)
        throws IOException {
        synchronized (this) {
          long oldPos = getPos();
          int nread = -1;
          try {
            seek(position);
            nread = read(buffer, offset, length);
          } finally {
            seek(oldPos);
          }
          return nread;
        }
      }
```

What this does is it reads a chunk and resets file pointer the same oldPos every time. This leads to huge amount of seek calls on S3 when a file is read which needs multiple iterations of this method which degrades performance a lot.

The fix avoids these seeks by not using this method. 
Also PrestoS3FileSystem opens new inputStream for each split so we need not worry about synchronization.

### CODE REVIEW

**Comment by electrum** [comment]
I think a better solution is to fix `PrestoS3FileSystem` by changing the class to keep track of the logical position separately from the physical position. We probably need to override that `readFully()` method in order to preserve the proper behavior for `seek()`.

**Comment by walterking** [comment]
I haven't had a chance to test in the real world, but I overrode read(long position, byte[] buffer, int offset, int length) inside of prestos3fs with a straight call to the s3 api and saw pretty good improvement.  

The big problem that I was seeing is the http request has abort() called on it, which invalidates the connection, so it renegotiates tcp/ssl every seek

**Comment by stagraqubole** [comment]
@walterking yes, re-connect because of seeks is the culprit. This change is similar to yours but at a couple of layer higher.

@electrum Yes, overriding readFully in PrestoS3FSInputStream would be better, it will hide these details from prestos3FS client, I can make that change. But I did not understand the first part about keeping track of logical and physical positions, can you please elaborate on that.

**Comment by electrum** [comment]
@stagraqubole, we can change `readFully()` to use underlying S3 input stream without calling `seek()`, with the same heuristic for seeking ahead if the gap is small. Doing this requires keeping track of the physical position of the underlying S3 input stream separately from the logical position of the `PrestoS3InputStream`.

Example:

* create stream: logical=0, physical=0
* `read()` 10 bytes: logical=10, physical=0
* `readFully` 10 bytes at position 30: logical=10, physical=40
* `seek()` 50 bytes: logical=60, physical=60

This would allow reading the entire file sequentially in chunks with `readFully()` using a single S3 input stream.

**Comment by stagraqubole** [comment]
I am sorry but I still to get the need of logical and physical positions. If these are only for letting seek work as in the example you mentioned then we dont need them as seek uses absolute position in argument.

Shouldn't something as simple as this be enough: 
override readFully in PrestoS3InputStream something like this:
```java
readFully(pos, buf, bufferOffset, len) {
	if len > 0
		seek(pos); // this will take care of the not opening new connection if seek is close to current position
		nbytes = read(buf, bufferOffset, len)
		readFully(pos + nread, buf, bufferOffset + nread, len - nread)	
}
```

**Comment by dain** [comment]
Superseded by #2766

**Comment by electrum** [comment]
The proposed change would break the API: a positioned read should not change the stream position. (Not a problem for ORC since it doesn't mix read types but other readers might.)

**Pull request closed without merging**
