### PR TITLE
Make system.runtime.queries run on coordinator

### PR DESCRIPTION
**Pull request by yuananf**
When we run query over table system.runtime.queries, it should only be run on coordinator.

### CODE REVIEW

**Comment by electrum** [comment]
This is not really correct, since there can technically be multiple coordinators (though it doesn't yet work with things like shard assignment balancing or the new resource manager). System tables probably need a flag that says coordinator(s)-only.

**Comment by cberner** [comment]
@yuananf is there a particular problem that this fixes for you, or it just a performance optimization?

**Comment by yuananf** [comment]
@cberner It's just a performance optimization.

**Comment by yuananf** [comment]
@electrum that will make sense.

**Comment by yuananf** [comment]
Besides, I find that I can connect to any worker node and submit a query, is that the expected behavior? If so, this PR should be closed.

**Comment by electrum** [comment]
Rather than two booleans, should this be an enum? `ALL_NODES`, `ALL_COORDINATORS`, `SINGLE_COORDINATOR`

**Comment by yuananf** [comment]
Oh I got so many useless commit in this PR, will open another one.

**Comment by electrum** [comment]
FYI, you can force push over a branch to update the commits.

**Pull request closed without merging**
