### PR TITLE
Initial decimal support (approach 2)

### PR DESCRIPTION
**Pull request by losipiuk**
This is followup patch for initial decimal implementation (issue #2797).

What changed in this pull request:

As we discussed this includes coercion support between decimal types.
Where possible we also defined decimal UDFs using annotation based approach.
To limit the number of actual UDF implementations we depend on coercion when possible.
E.g. We define add operator only for (DECIMAL(p,s), DECIMAL(p,s)).
This is not feasible for many operators though. So implementation of *,/,% and inequality was not changed and uses builder. 

Code is also rebased on top of master.

### CODE REVIEW

**Comment by losipiuk** [comment]
This relates to #2797

**Comment by losipiuk** [comment]
It would be great to have it in master and then do the refactoring work around type system.

@dain how is your VARCHAR patch. Do you want to make any changes to it. Maybe we should just push it without major changes and refactor afterwards.

**Comment by losipiuk** [comment]
It would also be great to meet to discuss limitations of this approach and next steps in typesystem area.

cc: @dain, @martint, @cberner, @ilfrin, @sopel39

**Comment by losipiuk** [comment]
I rebased this PR on top of master.
There is also another PR (https://github.com/Teradata/presto/pull/60) with some extra fixes of unit tests related to introduction of parametrized varchar type. This fixes are rather hacky. Maybe @dain can make some use of them when working on target shape of varchar patches.

How is work on that btw ;) ?

cc: @martint, @ilfrin

**Comment by martint** [comment]
I'm going to skip the first few commits until they are rebased on the results of https://github.com/facebook/presto/issues/3938

**Comment by losipiuk** [comment]
superseded by https://github.com/Teradata/presto/pull/89.

**Pull request closed without merging**
