### PR TITLE
only allow HTTP on discovery node

### PR DESCRIPTION
**Pull request by zhenyuy-fb**

### CODE REVIEW

**Comment by martint** [comment]
What's the purpose of this change?

**Comment by zhenyuy-fb** [comment]
The HTTPS endpoint will only serve the traffic from client to coordinators, besides, Presto will still expose HTTP endpoints for the following communications:
Presto discovery service: connected by workers
Presto workers: connected by the coordinator and other workers
For each Presto instance, the coordinator and the workers are always running from the same cluster. It is not needed for these internal endpoints to be secured as long as the ports are not opened through the firewall.

**Comment by wdong87** [comment]
Just to clarify, without this fix, we cannot start Presto coordinator because the discovery client running from the coordinator tries with HTTPS endpoint first and it would fail due to lack of proper settings (client-side cert/key path and Kerberos config). We only need HTTP communication between coordinator and the discovery endpoints (workers).

**Comment by wdong87** [comment]
@martint / @dain , could you merge this pull request as discussed :)? Thanks!

**Comment by martint** [comment]
I made a small tweak (prefer http over https) and merged it. Thanks.

**Comment by vbsoni** [comment]
Hi,

We are in a need where HTTP communication between server is totally blocked.

So we need to have HTTPS port opened between servers and need to have HTTPS communication between coordinator and worker nodes. 

Need guidance.

Regards,
Vicky

**Comment by mattsfuller** [comment]
Hi Vicky,
We here at Teradata are actively working on this. There should be a pull request we are putting up soon. We will let you know.
- Matt

**Pull request closed without merging**
