### PR TITLE
Look up parquet columns by name case-insensitively

### PR DESCRIPTION
**Pull request by billonahill**
Parquet schemas are case sensitive but hive is not so camelCase parquet fields are not found when accessed as lowercase hive columns.

### CODE REVIEW

**Comment by billonahill** [comment]
No, nested fields with caps are still broken (IQ-129).

**Comment by dain** [comment]
@zhenxiao, does this look good to you?  Also, any ideas on how we can test for this?

**Comment by zhenxiao** [comment]
@dain @billonahill the fix looks good to me. 
Kind of difficult to reproduce it in our current test case. Let me think of a way.

**Comment by billonahill** [comment]
@dain @zhenxiao yeah, I also looked at the tests to see how to verify this in a test case but I came up blank. Let me know if you have any ideas.

Also, since submitting this patch I released that we need to further patch the twitter fork to handle hive reserved words. When a parquet field is a reserved Hive word (i.e., ```keyword```, ```location```), we append an '_' to the field name before adding to Hive. This works fine when looking up presto columns by position, but not by name. As a result we also need to check for a match after stripping the _ (see  https://github.com/twitter-forks/presto/pull/32/files). This isn't something we want in the OSS master but I am curious how others deal with reserved Hive keywords.

**Comment by nezihyigitbasi** [comment]
@dain @billonahill @zhenxiao I created a PR for a simple unit test.

**Comment by zhenxiao** [comment]
@dain @billonahill 
@nezihyigitbasi 's PR looks good to me. What do you think?

**Comment by billonahill** [comment]
@dain @zhenxiao unit tests look good to me. Thanks @nezihyigitbasi!

I just refactored this patch to be easier to further patch on a private branch, like we're doing in https://github.com/twitter-forks/presto/pull/32/files.

**Comment by dain** [comment]
Merged, thanks!

**Pull request closed without merging**
