### PR TITLE
Port example http connector to TableLayout API

### PR DESCRIPTION
**Pull request by zhenxiao**
Fix https://github.com/facebook/presto/issues/2709

### CODE REVIEW

**Comment by zhenxiao** [comment]
Kindly ping
@haozhun @electrum @martint

**Comment by haozhun** [comment]
Remove all occurrences of ConnectorPartition from presto-example-http

**Comment by haozhun** [comment]
Instead, it looks like ExamplePartition may be removed entirely?

**Comment by haozhun** [comment]
Please ping us again after addressing the comments.

**Comment by zhenxiao** [comment]
thank you @haozhun get comments addressed

**Comment by haozhun** [comment]
@martint @electrum This PR seems good.

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request closed without merging**
