### PR TITLE
Add max/min to Date and Timestamp

### PR DESCRIPTION
**Pull request by haozhun**
@electrum Is this what you want? If so, I'll go ahead and add support for the other types.

### CODE REVIEW

**Comment by martint** [comment]
Instead of creating specialized implementation for each type, we should change max/min to work as a parametric function defined for any type that has the "orderable" trait.

**Comment by electrum** [comment]
We discussed this today. It isn't possible to make them generic yet because the compare methods on Type work on blocks. So for now, we'll just implement the temporal versions because it is really annoying not to have them and they need to be fast.

**Comment by martint** [comment]
Isn't that what max_by/min_by are doing?

**Comment by cberner** [comment]
@electrum we can make them generic by doing a lookup in the FunctionRegistry. You don't need to use the methods on Type, although it will be more work

**Comment by electrum** [comment]
I think those create blocks and are much less efficient. But that's a good point about looking up the operators in the function registry.

**Comment by electrum** [comment]
We also need code gen for dynamic state classes.

**Comment by yuananf** [comment]
It would be great when this feature is added.
When hive partition is Date or Timestamp, "show partitions" will fail with following error:
Unexpected parameters (date/timestamp) for function max. Expected: max(boolean), max(double), max(bigint), max(varchar).

Hope this PR will remove the error.

**Comment by haozhun** [comment]
See #2446

**Pull request closed without merging**
