### PR TITLE
Rename task.shard.max-threads to task.split.max-threads

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by cberner** [comment]
I think task.max-concurrent-splits might be more descriptive. This sounds to me like it's the number of threads that each split gets

Sent from my HTC

----- Reply message -----

**Comment by martint** [comment]
I'm don't think even that is accurate. The number of splits being processed by a worker at any given time can be larger than that number. If anything, it should be named "worker threads", "runner threads" or "driver threads".

**Comment by electrum** [comment]
`task.max-split-threads`? I think that is the most descriptive to the end user.

**Comment by martint** [comment]
I'd go with `task.max-worker-threads`

**Comment by cberner** [comment]
That sounds fine to me

**Comment by martint** [comment]
Looks good. Don't forget to update the release notes.

**Pull request merged**
