### PR TITLE
Enabled referencing columns in Orc files by name

### PR DESCRIPTION
**Pull request by kadaan**
Enable columns in Orc files to be referenced by name when the 'hive.orc.use-column-names' property is set to 'true'

### CODE REVIEW

**Comment by kadaan** [comment]
Any feedback would be greatly appreciated.

**Comment by dain** [comment]
I have working on a high priority project for a while now.  I will attempt to review this in my spare time.

**Comment by kadaan** [comment]
Thanks for taking a look.  I completely understand how swamped you are.  Let me know if you have any questions.

**Comment by kadaan** [comment]
Is there anything I can do to facilitate this getting reviewed?

**Comment by dain** [comment]
No, it is on me, and I have been completely focused on the other project.  I'll try to get to this early Jan.

**Comment by kadaan** [comment]
Totally understand. I'll just keep checking in.  Happy Holidays!

**Comment by kadaan** [comment]
Hopefully you had a good holiday, but now that it is over I'm going to start pestering you again. :)

**Comment by kadaan** [comment]
@dain Is it possible for you to review this now?

**Comment by dain** [comment]
Merged, thanks!

**Comment by dain** [comment]
I made some changes before pushing.  Please let me know if I broke something for you.

**Comment by kadaan** [comment]
LGTM

Thanks!

**Pull request closed without merging**
