### PR TITLE
Fix incorrect handling of aggregation arguments

### PR DESCRIPTION
**Pull request by raghavsethi**

### CODE REVIEW

**Comment by raghavsethi** [comment]
Fixes #3714.

**Comment by cberner** [comment]
Do you think this might fix https://github.com/facebook/presto/issues/3770 also?

**Comment by raghavsethi** [comment]
Possibly, but #3770 has no repro steps.

**Comment by raghavsethi** [comment]
It's not the same as #3770, this one happens at plan time, not execution time.

**Comment by electrum** [comment]
Add an explanation of what is broken.

**Comment by raghavsethi** [comment]
You mean to the commit message? That'll be longer than 70 chars. The referenced issue has more details, but essentially we produce incorrect plans for queries which have multiple aggregations that require input to be cast differently.

**Comment by martint** [comment]
Only the first line in the commit needs to be short. You can include a longer explanation of what's broken and, if it's not entirely obvious from the code, how the change fixes it in the body of the commit message.

Looks good

**Pull request merged**
