### PR TITLE
Implement DELETE

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by damiencarol** [comment]
@electrum Does HIVE Transactions will be used ?
https://cwiki.apache.org/confluence/display/Hive/Hive+Transactions

**Comment by electrum** [comment]
For now, we are only adding this for Raptor, but it should be possible to support Hive in the future.

**Comment by damiencarol** [comment]
My opinion is that, DELETE/UPDATE modify data and should support some sort of transaction API, no?
Do you plan to add ACID properties or transactions in core?

**Comment by electrum** [comment]
Presto already supports ACID for insert and delete operations (for connectors that can support it). Raptor is fully ACID for reads and writes. Long term, we definitely plan to support transactions in Presto (and Raptor), including all DML and DDL operations (like PostgreSQL supports).

**Comment by electrum** [comment]
If you look at the `ConnectorMetadata` interface, you'll see that all the write operations are done as begin/commit, allowing them to be implemented transactionally (for a single statement -- no multi-statement transactions).

**Comment by electrum** [comment]
@martint should look at the planning bits

**Comment by damiencarol** [comment]
Yep I saw the begin/commit primitives. I wander if we can use it with HIVE transactions in hive connector.
In this way:
in begin: 
* get transaction in HIVE metastore
* try to do the job

in commit:
* validate the transaction

**Comment by cberner** [comment]
This needs release notes

**Comment by cberner** [comment]
Looks like Travis is failing consistently for your PR (I already rebuilt it)

**Comment by cberner** [comment]
Assign back to me when you're done with the comments

**Comment by cberner** [comment]
Couple comments, but everything except the last commit looks good. @nileema should review that one, since I'm not familiar with the Raptor code

**Comment by nileema** [comment]
Looks good.

**Pull request merged**
