### PR TITLE
Add flexibility to Hive connector related to storage decisions

### PR DESCRIPTION
**Pull request by haozhun**

### CODE REVIEW

**Comment by cberner** [comment]
I think the tests are broken. Can you check Travis?

**Comment by electrum** [comment]
The design of this is weird. It is called a `LocationService`, but it isn't really a service, it is more of a serialized object that also contains logic. One way to improve this is to separate the object from the service.

**Comment by electrum** [comment]
@dain should review this

**Comment by cberner** [comment]
Had a few comments. Assign to @dain when you're done

**Comment by haozhun** [comment]
@dain Chris has did a first pass. He asked me to assign this to you.

**Comment by dain** [comment]
Some comments, but looks good.

**Comment by cberner** [comment]
Looks good to me too

**Pull request merged**
