### PR TITLE
Add unit test for quoted identifiers in JDBC

### PR DESCRIPTION
**Pull request by cawallin**
Test for https://github.com/facebook/presto/commit/2bddc7db8cda376b09dac49aaa1372be5850325d

### CODE REVIEW

**Comment by electrum** [comment]
Can you explain the rationale for this test? It doesn't seem related to `getIdentifierQuoteString()`.

**Comment by cawallin** [comment]
This test makes sure that you can use quotes around identifiers when submitting queries via JDBC; I did not test it without the patch, but I presumed the driver would use the ``getIdentifierQuoteString()`` field, and this would fail without it. Should it instead use getIdentifierQuoteString() to specify the way to quote SELECT?

**Comment by cawallin** [comment]
Update: I will indeed change it to use getIdentifierQuoteString, so we change the JDBC driver if the quote string ever changes.

**Comment by cawallin** [comment]
@electrum updated, thanks for the review

**Comment by electrum** [comment]
I don't think it is a useful test. The driver does not parse or otherwise do anything with the query string that would be affected by quotes. That method simply returns a constant, as most methods that class do. The value won't ever change -- it is part of the standard SQL grammar.

(As a user of JDBC, the method will return different values when using databases that use non-standard quotes. And databases like MySQL that support changing the identifier on a per-session basis can return different values. But Presto will not.)

**Comment by cawallin** [comment]
This test shows that Presto meets the SQL standard at least, and one mentality with testing is that you don't support it unless you test it, but I'm fine with just closing this PR.

**Comment by electrum** [comment]
We definitely test this in the server integration tests. There isn't anything JDBC specific about this test, so if you test this, where do you draw the line?

(More generally, we could consider having a version of the integration tests that runs the queries using the JDBC driver, but that's a different discussion.)

**Pull request closed without merging**
