### PR TITLE
Made maps comparable

### PR DESCRIPTION
**Pull request by bcrfb**
Added EQUAL and NOT_EQUAL operators for maps.

### CODE REVIEW

**Comment by martint** [comment]
In SQL, null means "a value exists but is unknown" so any comparison involving nulls should result in a null value.

**Comment by bcrfb** [comment]
Changed the comparisons so that an equals comparison between two maps with null values returns null if there are no key/value pairs that differ where both of the values are not null, and returns false otherwise. Not equals returns null if equals is null, otherwise it returns the opposite of equals.

**Comment by bcrfb** [comment]
I think the Travis build failure isn't due to my changes. The tests pass on my local machine, and I don't think I touched anything that would affect the test that failed in the Travis build.

Let me know if there's anything I need to do or if this can be merged.

**Comment by martint** [comment]
I made a few minor changes and merged it. Thanks!

**Pull request closed without merging**
