### PR TITLE
Use task instance ID to identify remote task uniquely

### PR DESCRIPTION
**Pull request by nileema**

### CODE REVIEW

**Comment by martint** [comment]
Explain what problem this addresses in the commit message

**Comment by dain** [comment]
You can squash the first two commits into a "Remove unused method and field"

**Comment by dain** [comment]
I think the last commit would be simpler if you required the task instance id to always be present.

**Comment by nileema** [comment]
@dain Updated

**Comment by dain** [comment]
Looks good

**Pull request merged**
