### PR TITLE
Fix nullif and isDistinctFrom code generation

### PR DESCRIPTION
**Pull request by arhimondr**
During the DECIMAL type development we have introduced operators that might accept arguments with different java types. For such cases `nullif` and `isDistinctFrom` code generation was failing.

### CODE REVIEW

**Comment by haozhun** [comment]
@martint I need some context on this. Are we introducing equals operator for different types?

**Comment by haozhun** [comment]
@martint For the `nullif` change, I have the same question about equals operator for different types. Did we decide to introduce equals operator for different types?

**Comment by arhimondr** [comment]
@haozhun This is complicated actually :-) We are going to introduce equals operators for decimal that accept arguments with the different java types. Currently in #4626 implementation we are always casting both arguments to the same decimal type before invoking any decimal operators. So, i can't reproduce the issue based on that branch. But we are about to create yet another PR which introduces DECIMAL coercion (https://github.com/Teradata/presto/tree/decimal_coercions). We refactored the `matchAndBind` algorightm, so the casting decimal arguments to the same type is no longer required. That's where i found this problem. I'm fine with puting this patch together with the `decimal_coercions` PR, but i thought that it might be usefull in general to push this small fix apart.

**Comment by haozhun** [comment]
Splitted into 3 commits. Merged.

**Comment by arhimondr** [comment]
@haozhun Thanks :+1:

**Pull request closed without merging**
