### PR TITLE
Only pushdown deterministic predicate

### LINKED ISSUE #2036: Exception when using non-deterministic predicate together with IN
The following query:

``` sql
SELECT * FROM (VALUES (1)) t(a) WHERE rand() > 0 and a IN (VALUES (1));
```

fails with this exception:

```
java.lang.IllegalArgumentException: Only deterministic expressions may be considered for rewrite
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at com.facebook.presto.sql.planner.EqualityInference.rewriteExpression(EqualityInference.java:101)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteSemiJoin(PredicatePushDown.java:677)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteSemiJoin(PredicatePushDown.java:134)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitSemiJoin(PlanRewriter.java:449)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitSemiJoin(PlanRewriter.java:65)
    at com.facebook.presto.sql.planner.plan.SemiJoinNode.accept(SemiJoinNode.java:120)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.rewrite(PlanRewriter.java:42)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteFilter(PredicatePushDown.java:219)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteFilter(PredicatePushDown.java:134)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitFilter(PlanRewriter.java:200)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitFilter(PlanRewriter.java:65)
    at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.rewrite(PlanRewriter.java:42)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitProject(PlanRewriter.java:244)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitProject(PlanRewriter.java:65)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.defaultRewrite(PlanRewriter.java:50)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteProject(PredicatePushDown.java:178)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteProject(PredicatePushDown.java:134)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitProject(PlanRewriter.java:238)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitProject(PlanRewriter.java:65)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.rewrite(PlanRewriter.java:42)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitOutput(PlanRewriter.java:282)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitOutput(PlanRewriter.java:65)
    at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.defaultRewrite(PlanRewriter.java:50)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteNode(PredicatePushDown.java:166)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.rewriteNode(PredicatePushDown.java:134)
    at com.facebook.presto.sql.planner.plan.PlanNodeRewriter.rewriteOutput(PlanNodeRewriter.java:120)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitOutput(PlanRewriter.java:276)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewritingVisitor.visitOutput(PlanRewriter.java:65)
    at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.rewrite(PlanRewriter.java:42)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.rewriteWith(PlanRewriter.java:31)
    at com.facebook.presto.sql.planner.optimizations.PredicatePushDown.optimize(PredicatePushDown.java:131)
    at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:88)
    at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:104)
    at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:66)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.getQueryPlan(StatementAnalyzer.java:510)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:479)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:106)
    at com.facebook.presto.sql.tree.Explain.accept(Explain.java:54)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
    at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
    at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:206)
    at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:191)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:152)
    at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QuerySubmitter$2.run(SqlQueryManager.java:490)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by yuananf**
Fix #2036 
@martint do you think this is the right approach?

### CODE REVIEW

**Comment by martint** [comment]
Can you explain what was causing the bug in the first place (I haven't analyzed the issue in detail)? 

I can't think of a reason why in general it would be wrong to push down a non-deterministic predicate, so this fix looks overly broad and would appear to be masking the underlying bug instead of fixing it.

**Comment by yuananf** [comment]
For this query 
```
SELECT * FROM (VALUES (1)) t(a) WHERE rand() > 0 and a IN (VALUES (1));
```
The IN clause will generate a semijoin node, and the predicate pushdown optimizer tried to pushdown the filter rand() > 0 to the semijoin node, thus will cause the exception.

I think you are right, current fix is too broad.
I will find another solution.

**Comment by cberner** [comment]
@yuananf if you're working on a different solution should we close this PR?

**Comment by yuananf** [comment]
@cberner yes, sure! Will open another one when it's done.

**Pull request closed without merging**
