### PR TITLE
Change web interface to use ReactJS and Bootstrap3

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by electrum** [comment]
screen shot 2015-04-09 at 5 36 56 pm

Overall looks good, but there some issues to fix:
* Something is weird with the running queries table. It is missing column headers.
* The "Completed" header is chopped off on completed queries.
* The query ID should not be wrapped. If space is an issue, maybe we could use a smaller font for it?
* The completed queries (and maybe the running ones?) seem to be in a random order, and the order might change as the table is updated.
* The error column for completed queries is always empty.

**Comment by cberner** [comment]
Oops, ya I missed the sorting code when I refactored it. I put that back, chmod'ed the files, and fixed the error code display. 

The rest of the comments are addressed by the last commit (which I just added). It makes the query list responsive, so you can resize your browser window, and you should even be able to view it on a phone

**Comment by electrum** [comment]
This looks much better! A few minor issues:
* The top has a not-quite-full-width gray bar rather than a full width black bar like the bottom.
* There is a lot of wasted space for the header at the top. (I also want to replace that with a header similar to the website that has a logo...)
* The continuation dots for a long query wastes an entire line. Maybe put them at the end of the last query line?
* Three query lines ends up making the row larger, which is distracting and actually seems unnecessary given that we already have three lines for the other data.

screen shot 2015-04-13 at 4 43 32 pm

**Comment by cberner** [comment]
I removed the line. The wasted space is a pre-existing issue on master, and the "..." on the next line is just an issue with your screen resolution (try resizing the window). The codebox styling takes up more space, but I think it looks nicer, and even if I remove it we'll still have the same problem: it'll just be for queries that are 4 lines instead of 3 lines. Unless, we want to truncate any query > 3 lines

**Comment by dain** [comment]
I think we can change `Completed splits: 17/17` to `Completed splits: 17`, since this line only shows up at the end of the query.

**Comment by cberner** [comment]
I'm fine with that, but it's not necessarily `n/n` you can have `15/17` since a query can complete before all its splits, but after those splits have been discovered

**Comment by dain** [comment]
Since the total isn't accurate anyway, I don't see any reason to show it.

**Comment by cberner** [comment]
Works for me. I only included it because it was on the old version. I've removed it

**Comment by electrum** [comment]
New version looks great!

**Comment by cberner** [comment]
Added a button to toggle auto-refresh too

**Comment by haozhun** [comment]
I believe it's wrong to pass any non-trivial function to `setInterval`, as pointed out [here](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setInterval#Dangerous_usage). The correct thing to do should be something like

    loadQueriesFromServer: function(finishCallback)
    {
        d3.json('/v1/query', function (queries) {
            this.replaceState({queries: queries});
            if (this.state.autoRefresh) {
                this.setState({queries: queries});
            }
            finishCallback();
        }.bind(this));
    }

    var loopRefresh = function loop() {
        loadQueriesFromServer(function() {
            setTimeout(loop, 1000);
        }
    };

    componentDidMount: function() {
         this.loopRefresh();
    }

**Comment by haozhun** [comment]
In addition, I don't like the idea of having an `if` on `autoRefresh` and keep the loop running even when auto-refresh is off. But one can argue that code is cleaner this way.

Either way, I believe it makes more sense to pull the if out of `d3.json` so that no network traffic is triggered when auto-refresh is off.

**Comment by haozhun** [comment]
Besides, I believe it is more convenient (but less intuitive) to use a keystroke instead of a checkbox to control the status of autorefresh. When you want to click on a query. You don't want to move your mouse to a checkbox first.

**Comment by cberner** [comment]
Good to know about setInterval! I refactored it to use setTimeout(). @haozhun is there a reason to have the wrapper method for recursion, instead of the way I did it? That seemed unnecessary. Changed the auto-refresh to not make a network call, unless necessary too

**Comment by haozhun** [comment]
I feel it's a reasonable abstraction to separate the loop logic and loadQueries logic. I feel `loadQueriesFromServer` shouldn't need to worry about loop/interval of any kind. And having a finish callback is natural in any js function that is asynchronous.

**Comment by cberner** [comment]
Makes sense. I put the loop in

**Comment by electrum** [comment]
Looks good

**Pull request merged**
