### PR TITLE
Add testcases for reading Parquet

### PR DESCRIPTION
**Pull request by zhenxiao**
following @dain 's ORC testcases, add testcases for Parquet

### CODE REVIEW

**Comment by dain** [comment]
Can you supress the logging for parquet?  In Travis ~50% of the log lines are from parquet, and is so large the logs are getting truncated: https://s3.amazonaws.com/archive.travis-ci.org/jobs/83993741/log.txt

**Comment by zhenxiao** [comment]
@dain did not find a good way to disable the logs, let me ask david for some help
Hi @electrum when adding tests for parquet, get so many logs from parquet-hadoop, parquet-column, etc. Is there a good way to disable logging from parquet modules? I tried playing with it, did not get much progress, do you have any suggestions? thanks!

**Comment by zhenxiao** [comment]
@dain thanks @electrum 's help. I set these logging level to WARNING in beforeClass
those are all from parquet writer classes

**Comment by zhenxiao** [comment]
rebased to the current master @dain would you please review it?

**Comment by zhenxiao** [comment]
Merged into the New Parquet Reader bug fix PR:
https://github.com/facebook/presto/pull/4000

**Pull request closed without merging**
