### PR TITLE
Fix compiling primitive class constants

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by cberner** [comment]
Looks good

**Comment by martint** [comment]
what's broken?

**Comment by cberner** [comment]
@martint I'm trying to implement lambdas and this broke my compiler

**Comment by martint** [comment]
I guess I was hoping for an explanation in the commit message. "Fix broken X" is too vague

**Comment by electrum** [comment]
They didn't work at all, so more like implement it (wasn't used anywhere).

**Comment by electrum** [comment]
Primitives classes don't have a name and thus can't be in the constant pool, so they need special handing.

**Pull request closed without merging**
