### PR TITLE
Add support for views to JDBC connectors

### PR DESCRIPTION
**Pull request by harunurhan**
Related issue: #4161 

I am not sure if tests are necessary here, l can remove them if not required.

### CODE REVIEW

**Comment by albertocsm** [comment]
any progress on this one?

**Comment by ninalb** [comment]
i have no idea how github works i am new but i am dying till the day i find
those secrets i need

**Comment by albertocsm** [comment]
BTW, this will not affect MySQL as MySqlClient [overrides](https://github.com/facebook/presto/blob/master/presto-mysql/src/main/java/com/facebook/presto/plugin/mysql/MySqlClient.java#L97) the getTables method

**Comment by harunurhan** [comment]
@albertocsm  yes you are right but issue is only about the jdbc connectors. I can modify it though if requested.

**Comment by electrum** [comment]
This needs a test in `TestMySqlDistributedQueries` and `TestPostgreSqlDistributedQueries` that actually runs a query against a view. I'm adding it. Also, the change in `MySqlClient` is required as noted by @albertocsm.

**Comment by electrum** [comment]
Merged, thanks!

**Comment by the6campbells** [comment]
Builds 138 and 137 fail to return tables of type VIEW when Presto consuming Postgres.

**Pull request closed without merging**
