### PR TITLE
Add bucket support for Raptor

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by nileema** [comment]
Bunch of comments, nothing major. 
Looks good overall.

**Comment by electrum** [comment]
Updated with all review comments

**Comment by nileema** [comment]
Saw an error when the table did not have any rows: https://gist.github.com/nileema/dc4f7c7c0599dde8682b

**Comment by electrum** [comment]
@nileema, the line numbers don't match up with the current code. I think that error is already fixed. It checks for `resultSet.isBeforeFirst()`

**Pull request merged**
