### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by electrum** [comment]
Looks good expects for distributed joins. If we do decide to enable it by default, we need to clearly document this including the session property (should do this in any case).

**Comment by dain** [comment]
@electrum where do you want to document session properties?  They are now self documenting, run show session, so I am a bit concerned about having two locations for documentation.

**Comment by electrum** [comment]
For something like distributed joins, we should have a section that explains the feature and trade off, and lists the config option and session option.

This should be in a new configuration chapter that comes after the deployment chapter.

**Comment by electrum** [comment]
Looks good

**Pull request merged**
