### PR TITLE
Add coercion for joing using and equi-join

### PR DESCRIPTION
**Pull request by yuananf**
based on #2542

### CODE REVIEW

**Comment by cberner** [comment]
@erichwang do you have time to review this? If not, assign to @dain

**Comment by martint** [comment]
This fixes the problem for `JOIN ... USING`, but it still fails with a regular equality joins:

```
SELECT * FROM (VALUES (1.0, 2.0)) x (a, b) JOIN (VALUES (1, 3)) y (a, b) ON x.a = y.b
```

**Comment by yuananf** [comment]
@martint I add a commit to fix this one.

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
