### PR TITLE
Split large pages

### LINKED ISSUE #2060: Split pages if necessary before sending them over the network
Pages provided by plugin data sources can be arbitrarily sized relative to the maximum HTTP payload size (default 16MB). This can cause query failures with:

```
com.facebook.presto.operator.PageTooLargeException: Remote page is too large
	at com.facebook.presto.operator.HttpPageBufferClient.rewriteException(HttpPageBufferClient.java:396)
	at com.facebook.presto.operator.HttpPageBufferClient.access$1000(HttpPageBufferClient.java:71)
	at com.facebook.presto.operator.HttpPageBufferClient$2.onFailure(HttpPageBufferClient.java:321)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

We should probably split the pages if necessary before sending them over HTTP.

An example of this happening is with the Hive ORC reader in which it turns each data segment into a page without regard to total page size maximums.

### PR DESCRIPTION
**Pull request by nileema**
Fixes #2060

### CODE REVIEW

**Comment by dain** [comment]
looks good

**Comment by dain** [comment]
Oh ya, you should add a test that gets regions from an empty page.

**Comment by dain** [comment]
looks good

**Comment by nileema** [comment]
This is merged.

**Pull request closed without merging**
