### PR TITLE
Remove jetbrains' annotation from code

### PR DESCRIPTION
**Pull request by losipiuk**
org.jetbrains.annotations.NotNull is replaced with
javax.annotation.Nullable.

### CODE REVIEW

**Comment by kokosing** [comment]
looks good

**Comment by electrum** [comment]
We should actually remove `@NotNull` entirely since that is the default for the code base.

**Comment by electrum** [comment]
I created #4743 to remove these and add a Checkstyle rule.

**Comment by electrum** [comment]
Note that `javax.validation.constraints.NotNull` is not the opposite of `javax.annotation.Nullable`. It is part of Bean Validation (JSR 303). We use it for config objects which are validated using bean validation. A method marked as `@NotNull` can actually return null, just like a method annotated with `@Max(5)` can return a number bigger than that.

**Pull request closed without merging**
