### PR TITLE
 Add support Using Prepared Statements

### PR DESCRIPTION
**Pull request by han-wang**

### CODE REVIEW

**Comment by rschlussel** [comment]
There's work in progress to add support for prepared statements on the server side via sql queries.  The first pull request for this is https://github.com/facebook/presto/pull/4412.  (You can find the rest at https://github.com/Teradata/presto/commits/prepared-statements, just waiting for the first bit to get accepted).   The JDBC driver should then handle them similarly to how it handles session variables.

**Comment by petroav** [comment]
This issue (https://github.com/facebook/presto/issues/4338) contains a description of the functionality implemented in the branch that @rschlussel linked to. Feel free to try out the branch and let us know if you run into any problems.

**Comment by han-wang** [comment]
thanks

**Comment by kc14** [comment]
What happened to the Prepared Statement Code in the presto master? It still seems not implement there ... was it rejected? I use PDI/Kettle/Spoon and it would be great to have prepared statements. So that Kettle could get the meta info about the result set of the query without an actual query ...
Thanks for any info in advance.

**Comment by rschlussel** [comment]
@kc14 The Presto server has prepared statement support, but it has not yet been added to the JDBC driver (see #6158).  You can use Teradata's JDBC driver for Presto (free but not open source) if you'd like to take advantage of Presto's prepared statement functionality.

**Comment by mambistats** [comment]
@rschlussel Thanks for your recommendation ... we are already doing that and until now it seems to work fine. But personally I would prefer to have these changes also in the open source JDBC driver. And as far as I can see ... I do not understand why they are not able to merge this pull request ... do you know what the problem here is?

**Comment by rschlussel** [comment]
@mambistats This PR doesn't use the server support for prepared statements.  We definitely would like to have support for prepared statements in the open source driver, though.  If you're interested in working on this, a PR would be welcome.  Coordinate with @nahi who started work on this (not sure where it stands) and check out issue #6158.

**Pull request closed without merging**
